name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline \
            -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -F ref=main
