name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/71098870/trigger/pipeline \
            -F token=glptt-c14f5b22dfb049901ba0e4f0a94395fa7bbd5110 \
            -F ref=main
